DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME TEXT NOT NULL,
    PRODUCT_NAME TEXT,
    EXPORT_COUNTRY TEXT,
    ORDER_VALUE REAL
);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, PRODUCT_NAME, EXPORT_COUNTRY, ORDER_VALUE)
VALUES
    (1, 'Alice Smith', 'Solar Panels', 'Germany', 5000),
    (2, 'Victor Hugo', 'Wind Turbines', 'France', 12000),
    (3, 'Aaron Burr', 'Batteries', 'USA', 3000),
    (4, 'George Taylor', 'Solar Panels', 'Germany', 4500),
    (5, 'Amanda Ross', 'Inverters', 'Canada', 2500),
    (6, 'Dorian Gray', 'Turbines', 'UK', 7000),
    (7, 'Alex Johnson', 'Batteries', 'USA', 3200),
    (8, 'Eleanor Rigby', 'Cables', 'France', 1500);


SELECT * FROM CUSTOMERS 
WHERE CUSTOMER_NAME LIKE 'A%';

SELECT * FROM CUSTOMERS 
WHERE CUSTOMER_NAME LIKE '%or%';

SELECT DISTINCT EXPORT_COUNTRY 
FROM CUSTOMERS;

SELECT CUSTOMER_NAME, PRODUCT_NAME, ORDER_VALUE
FROM CUSTOMERS
WHERE EXPORT_COUNTRY IN ('France', 'USA')
ORDER BY ORDER_VALUE DESC;

SELECT EXPORT_COUNTRY, SUM(ORDER_VALUE) AS Total_Sales
FROM CUSTOMERS
GROUP BY EXPORT_COUNTRY
ORDER BY Total_Sales DESC;