DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
    EMP_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    ROLE TEXT,
    DEPARTMENT TEXT,
    SALARY REAL,
    JOIN_DATE TEXT
);

INSERT INTO EMPLOYEES (EMP_ID, NAME, ROLE, DEPARTMENT, SALARY, JOIN_DATE)
VALUES
    (1, 'Harsh', 'CEO', 'Management', 150000, '2020-01-01'),
    (2, 'Sara', 'Manager', 'Sales', 85000, '2021-03-15'),
    (3, 'James', 'Developer', 'Engineering', 95000, '2022-06-10'),
    (4, 'Maria', 'Analyst', 'Finance', 75000, '2021-11-20'),
    (5, 'Leo', 'Developer', 'Engineering', 98000, '2023-01-05'),
    (6, 'Chloe', 'Executive', 'Sales', 60000, '2022-09-12'),
    (7, 'Ryan', 'Analyst', 'Finance', 72000, '2020-05-30');

UPDATE EMPLOYEES 
SET SALARY = 65000 
WHERE NAME = 'Chloe';

SELECT 
    SUM(SALARY) AS Company_Total_Payroll,
    AVG(SALARY) AS Average_Salary
FROM EMPLOYEES;

SELECT DEPARTMENT, COUNT(*) AS Employee_Count
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(SALARY) AS Dept_Avg
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING Dept_Avg > 80000;

SELECT NAME, ROLE, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES 
WHERE JOIN_DATE > '2021-12-31'
ORDER BY JOIN_DATE ASC;